---

version: "3.5"

services:
        globus-proxy:
               #  image: tapis/globus-proxy-api
                build: .
                ports:
                        - "5000:5000"
                volumes:
                        - ./configschema.json:/home/tapis/configschema.json
                        - ./config-local.json:/home/tapis/config.json
                        - ./service.log:/home/tapis/service.log
        redis:
                image: redis
                ports:
                        - 6379:6379

