---

version: "3.5"

services:
    globus-proxy:
        # image: tapis/globus-proxy
        build: .
        ports:
            - "5000:5000"
        volumes:
            - ./configschema.json:/home/tapis/configschema.json
            - ./config-local.json:/home/tapis/config.json
            - ./service.log:/home/tapis/service.log
        container_name: globus-proxy

    # globus_proxy-tests:
    #     build: 
    #         context: ./
    #         dockerfile: ./Dockerfile-test
    #     volumes:
    #         - ./config-local.json:/home/tapis/config.json


