---

version: "3.5"

services:
    globus-proxy:
        image: tapis/globus-proxy:1.6.2
        volumes:
            - ./configschema.json:/home/tapis/configschema.json
            - ./config-local.json:/home/tapis/config.json
            - ./service.log:/home/tapis/service.log
            - ../gpsettings.json:/home/tapis/gpsettings.json
        container_name: globus-proxy
        networks: 
            - tapis

    # globus_proxy-tests:
    #     build: 
    #         context: ./
    #         dockerfile: ./Dockerfile-test
    #     volumes:
    #         - ./config-local.json:/home/tapis/config.json


networks:
    tapis:
        external: true
