---

version: "3.5"

services:
        globus-proxy:
                image: tapis/globus-proxy-api
                ports:
                        - "5001:5000"
                volumes:
                        - ./config-local.json:/home/tapis/config.json
                        - ./service.log:/home/tapis/service.log
 
