name: Docker Image CI

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Debug release name
      shell: bash
      run: echo ${{ steps.extract_branch.outputs.branch }}
    
    # - name: Checkout
    #   uses: actions/checkout@v3
      
    # - name: Login to Docker Hub
    #   uses: docker/login-action@v1
    #   with:
    #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
    #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag tapis/globus-proxy:${{ steps.extract_branch.outputs.branch }}
      
    # # if tag == prod release, tag as latest 
    # - name: Build the Docker image with latest tag
    #   if: ${{ steps.extract_branch.outputs.branch == 'prod' }}
    #   run: docker build . --file Dockerfile --tag tapis/globus-proxy:latest --tag tapis/globus-proxy:1.3.0
    
    # - name: Push the image to dockerhub
    #   run: docker push --all-tags tapis/globus-proxy
