name: Docker Image CI

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Debug release name
      shell: bash
      run: echo ${{ github.ref_name }}
    
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tapis/globus-proxy:${{ github.ref_name }}
    
    - name: Push the image to dockerhub
      run: docker push --all-tags tapis/globus-proxy
